# Generated by Django 6.1 on 2026-08-27 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_article_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscribed_journalists',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscribed_publishers',
        ),
    ]
