# Generated by Django 6.1 on 2026-08-28 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_user_subscribed_journalists_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('READER', 'Reader'), ('EDITOR', 'Editor'), ('JOURNALIST', 'Journalist'), ('PUBLISHER', 'Publisher')], default='READER', max_length=20),
        ),
    ]
