# Generated by Django 6.1 on 2026-08-30 18:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='publishers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'PUBLISHER'}, related_name='publisher_accounts', to=settings.AUTH_USER_MODEL),
        ),
    ]
