# Generated by Django 6.1

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Restore reader subscription relationships."""

    dependencies = [
        ("news", "0006_publisher_publishers"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="subscribed_journalists",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"role": "JOURNALIST"},
                related_name="journalist_subscribers",
                symmetrical=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="subscribed_publishers",
            field=models.ManyToManyField(
                blank=True,
                related_name="subscribers",
                to="news.publisher",
            ),
        ),
    ]
