from django.urls import path

from . import views


urlpatterns = [
    path("", views.home, name="home"),
    path("register/", views.register, name="register"),
    path("articles/", views.article_list, name="article_list"),
    path(
        "articles/<int:article_id>/",
        views.article_detail,
        name="article_detail",
    ),
    path("newsletters/", views.newsletter_list, name="newsletter_list"),
    path(
        "newsletters/<int:newsletter_id>/",
        views.newsletter_detail,
        name="newsletter_detail",
    ),
    path("publishers/", views.publisher_list, name="publisher_list"),
    path(
        "publishers/<int:publisher_id>/",
        views.publisher_detail,
        name="publisher_detail",
    ),
    path(
        "publisher/dashboard/",
        views.publisher_dashboard,
        name="publisher_dashboard",
    ),
    path(
        "publisher/create/",
        views.publisher_create,
        name="publisher_create",
    ),
    path(
        "publisher/<int:publisher_id>/edit/",
        views.publisher_edit,
        name="publisher_edit",
    ),
    path(
        "publisher/<int:publisher_id>/delete/",
        views.publisher_delete,
        name="publisher_delete",
    ),
    path(
        "subscriptions/",
        views.subscriptions,
        name="subscriptions",
    ),
    path(
        "journalist/dashboard/",
        views.journalist_dashboard,
        name="journalist_dashboard",
    ),
    path(
        "journalist/articles/create/",
        views.article_create,
        name="article_create",
    ),
    path(
        "journalist/articles/<int:article_id>/edit/",
        views.article_edit,
        name="article_edit",
    ),
    path(
        "journalist/articles/<int:article_id>/delete/",
        views.article_delete,
        name="article_delete",
    ),
    path(
        "journalist/newsletters/create/",
        views.newsletter_create,
        name="newsletter_create",
    ),
    path(
        "journalist/newsletters/<int:newsletter_id>/edit/",
        views.newsletter_edit,
        name="newsletter_edit",
    ),
    path(
        "journalist/newsletters/<int:pk>/delete/",
        views.newsletter_delete,
        name="newsletter_delete",
    ),
    path(
        "editor/dashboard/",
        views.editor_dashboard,
        name="editor_dashboard",
    ),
    path(
        "editor/articles/<int:article_id>/",
        views.editor_article_detail,
        name="editor_article_detail",
    ),
    path(
        "editor/articles/<int:article_id>/edit/",
        views.editor_article_edit,
        name="editor_article_edit",
    ),
    path(
        "editor/articles/<int:article_id>/delete/",
        views.editor_article_delete,
        name="editor_article_delete",
    ),
    path(
        "editor/newsletters/<int:newsletter_id>/edit/",
        views.editor_newsletter_edit,
        name="editor_newsletter_edit",
    ),
    path(
        "editor/newsletters/<int:newsletter_id>/delete/",
        views.editor_newsletter_delete,
        name="editor_newsletter_delete",
    ),
    path(
        "editor/articles/<int:article_id>/approve/",
        views.approve_article,
        name="approve_article",
    ),
    path(
        "api/articles/",
        views.ArticleListCreateAPI.as_view(),
        name="article-api-list",
    ),
    path(
        "api/articles/<int:article_id>/",
        views.ArticleDetailAPI.as_view(),
        name="article-api-detail",
    ),
]
